### ISSUE TITLE
will install.sh and export.sh effect the existing esp-idf development environment

### ISSUE THREAD

**Issue by goodluckrhj** [espressif/esp-wdf#1]
Before i begin to install esp-wdf, I have already installed esp-idf 4.4.3 from gitee and  used the alias "get-idf" is  to export  idf.py.

After a look at install.sh file, i wonder if it will effect the existing esp-idf development environment, e.g., the "IDF_PATH" already used by esp-idf projects.

**Comment by wujiangang** [comment]
You need to export idf and wdf in different terminals, otherwise, there will be a conflict.

**Comment by goodluckrhj** [comment]
> You need to export idf and wdf in different terminals, otherwise, there will be a conflict.

Thank you for reply.
Personally, I would like that espressif makes a distinction between them, because the files generated by the idf tool and the wdf tool are very different.
